export const DEFAULT_API_BASE_URL = 'https://intensityresearch.com/intensityapi'

export const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL || DEFAULT_API_BASE_URL).replace(/\/$/, '')

/**
 * Production Client origin (SPA).
 * Activation links are generated by the Intensity API. When its `frontend_activation_url`
 * setting is empty, emails use `{API}/auth/activate?token=...`. To open this Client instead,
 * the backend must set: frontend_activation_url = https://intensityresearch.com/verify-email?token={token}
 */
export const DEFAULT_CLIENT_APP_URL = 'https://intensityresearch.com'

export const CLIENT_APP_URL = (
  import.meta.env.VITE_CLIENT_BASE_URL ||
  (typeof window !== 'undefined' ? window.location.origin : DEFAULT_CLIENT_APP_URL)
).replace(/\/$/, '')

export function clientVerifyEmailUrl(token: string) {
  return `${CLIENT_APP_URL}/verify-email?token=${encodeURIComponent(token)}`
}

/** Deployed Client UI reset page. Email links must not use localhost or the current browser origin. */
export function clientResetPasswordPageUrl() {
  const origin = (import.meta.env.VITE_CLIENT_BASE_URL || DEFAULT_CLIENT_APP_URL).replace(/\/$/, '')
  return `${origin}/reset-password`
}
