import uberCard from '@/assets/rewards/uber.svg'
import uberEatsCard from '@/assets/rewards/uber-eats.svg'
import { countryName } from '@/content/countries'
import catalogData from '@/content/tremendousCatalog.json'
import type { PaymentMethod, PublicSettings } from '@/types/api'
import type { RewardCategory } from '@/types/common'

type SettingFlag = 'amazon_enabled' | 'flipkart_enabled'

interface CatalogOffer {
  currency: string
  countries: string[]
}

interface CatalogVariant {
  productId: string
  /** Tremendous' own product name, e.g. "Uber UK" — recorded with the request for fulfilment. */
  productName: string
  /** Name shown to members, e.g. "Uber" or "Amazon.co.uk". */
  name: string
  image: string
  offers: CatalogOffer[]
}

interface CatalogOption {
  key: string
  name: string
  category: RewardCategory
  paymentMethod: string
  setting?: SettingFlag
  variants: CatalogVariant[]
}

/** Generated by `npm run catalog:sync` from Tremendous' public catalog — do not edit by hand. */
export const tremendousCatalog = catalogData as { syncedAt: string; options: CatalogOption[] }

export interface RewardMethod {
  /** Stable option key; one per brand, so a reward never appears twice for a country. */
  id: string
  name: string
  image: string
  /** Intensity API payout method sent as payment_method / payment_methord. */
  apiValue: string
  category: RewardCategory
  shortLabel?: string
  /** The fields below are set once the method is resolved for a recipient country. */
  countryCode?: string
  productId?: string
  productName?: string
}

/** Enabled payout methods and switches from the Intensity API (/settings or /rewards/balance). */
export interface PanelPayoutConfig {
  methods?: PaymentMethod[] | null
  settings?: Partial<Pick<PublicSettings, 'paypal_enabled' | SettingFlag>> | null
}

/**
 * Tremendous serves the same combined Uber | Uber Eats card for both products.
 * Use distinct brand cards so each reward shows its own mark.
 */
const BRAND_CARD_IMAGES: Record<string, string> = {
  uber: uberCard,
  'uber-eats': uberEatsCard,
}

function catalogImage(option: CatalogOption, variant: CatalogVariant) {
  return BRAND_CARD_IMAGES[option.key] ?? variant.image
}

function methodEnabled(option: CatalogOption, config: PanelPayoutConfig) {
  const value = option.paymentMethod.trim().toLowerCase()
  const listed = (config.methods ?? []).some((method) => method.name.trim().toLowerCase() === value)
  const paypalSwitch = value === 'paypal' && config.settings?.paypal_enabled === 1
  if (!listed && !paypalSwitch) return false
  return !option.setting || config.settings?.[option.setting] !== 0
}

function variantCountries(variant: CatalogVariant) {
  return variant.offers.reduce((total, offer) => total + offer.countries.length, 0)
}

/** One entry per Tremendous brand, for showcases that are not tied to a recipient. */
export const showcaseRewardMethods: RewardMethod[] = tremendousCatalog.options.map((option) => ({
  id: option.key,
  name: option.name,
  image: catalogImage(option, option.variants[0]),
  apiValue: option.paymentMethod,
  category: option.category,
}))

/** Brands switched on by the panel, regardless of recipient country. */
export function panelShowcaseMethods(config: PanelPayoutConfig) {
  return showcaseRewardMethods.filter((method) => {
    const option = tremendousCatalog.options.find((item) => item.key === method.id)
    return option ? methodEnabled(option, config) : false
  })
}

/**
 * Rewards a recipient in `country` (ISO 3166-1 alpha-2) can actually receive: Tremendous must list
 * the product for that country without restrictions, and the panel must have its payout method on.
 * When a brand has several editions there, the most local one wins (Amazon.ca over Amazon.com).
 */
export function rewardMethodsForCountry(country: string, config: PanelPayoutConfig): RewardMethod[] {
  const methods: RewardMethod[] = []
  for (const option of tremendousCatalog.options) {
    if (!methodEnabled(option, config)) continue
    let best: CatalogVariant | undefined
    let display: CatalogVariant | undefined
    for (const variant of option.variants) {
      const offered = variant.offers.some((offer) => offer.countries.includes(country))
      if (!offered) continue
      // Variants are popularity-sorted; the first offered one is the canonical brand card.
      if (!display) display = variant
      if (!best || variantCountries(variant) < variantCountries(best)) best = variant
    }
    if (!best) continue
    methods.push({
      id: option.key,
      name: best.name,
      image: catalogImage(option, display ?? best),
      apiValue: option.paymentMethod,
      category: option.category,
      countryCode: country,
      productId: best.productId,
      productName: best.productName,
    })
  }
  return methods
}

export function describeRewardMethod(method: RewardMethod) {
  if (method.category === 'cash') return `Paid to your ${method.name} account once your request is approved.`
  if (method.category === 'digital') return `Prepaid ${method.name} card, issued once your request is approved.`
  return `Digital ${method.name} gift card, issued once your request is approved.`
}

/** Remark stored with the payout request so the exact Tremendous product can be fulfilled. */
export function redemptionRemark(method: RewardMethod, note = '') {
  const details = [
    method.productName ?? method.name,
    method.countryCode ? countryName(method.countryCode) || method.countryCode : '',
    method.productId ? `Tremendous ${method.productId}` : '',
  ].filter(Boolean)
  const trimmed = note.trim()
  return trimmed ? `${details.join(' · ')} — ${trimmed}` : details.join(' · ')
}

/** Best-effort mark for a stored request, from the product recorded in its remark or its payout method. */
export function resolveRequestMethod(paymentMethod?: string, remark?: string | null): RewardMethod | undefined {
  const text = (remark ?? '').toLowerCase()
  if (text) {
    for (const option of tremendousCatalog.options) {
      const variant = option.variants.find(
        (item) => text.includes(item.productId.toLowerCase()) || text.startsWith(item.productName.toLowerCase()),
      )
      const base = showcaseRewardMethods.find((method) => method.id === option.key)
      if (variant && base) {
        return { ...base, name: variant.name, image: catalogImage(option, variant), productName: variant.productName }
      }
    }
    const byName = [...showcaseRewardMethods]
      .sort((a, b) => b.name.length - a.name.length)
      .find((method) => text.startsWith(method.name.toLowerCase()))
    if (byName) return byName
  }
  if ((paymentMethod ?? '').trim().toLowerCase() === 'paypal') return showcaseRewardMethods.find((method) => method.id === 'paypal')
  return undefined
}
